version: '3.8'

services:
  mysql1:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rudALS1342!!
      MYSQL_DATABASE: user_database

  mysql2:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rudALS1342!!
      MYSQL_DATABASE: activity_database

  mysql3:
    image: mysql:latest
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rudALS1342!!
      MYSQL_DATABASE: newsfeed_database
