server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
  application:
    name: api-gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080/
          predicates:
            - Path=/user/**
        - id: activity-service
          uri: http://localhost:8081/
          predicates:
            - Path=/activity/**
        - id: newsfeed-service
          uri: http://localhost:8082/
          predicates:
            - Path=/newsfeed/**

  datasource:
    url: jdbc:mysql://localhost:3306/preorder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
